name: example
description: Example for mondrian
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.0-182.0.dev <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  mondrian:
    path: ../
  ltogt_utils_flutter:
    path: ../../ltogt_utils_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
